<?php

/**
 * Implements hook_menu().
 */
function campaign_monitor_subscribers_menu() {
  $items = array();
  $items['cm-list/%cm_list/subscribers'] = array(
    'title' => 'Subscribers',
    'page callback' => 'campaign_monitor_subscribers_list',
    'page arguments' => array(1),
    'access callback' => 'entity_access',
    'access arguments' => array('update', 'cm_list', 1),
    'type' => MENU_CALLBACK,
    'file' => 'includes/campaign_monitor_subscribers.pages.inc',
  );
  $items['cm-list/%cm_list/subscribers/active'] = array(
    'title' => 'Active',
    'type' => MENU_DEFAULT_LOCAL_TASK,
    'weight' => 1,
  );
  $items['cm-list/%cm_list/subscribers/unconfirmed'] = array(
    'title' => 'Unconfirmed',
    'page callback' => 'campaign_monitor_subscribers_list',
    'page arguments' => array(1, 3),
    'access callback' => 'entity_access',
    'access arguments' => array('update', 'cm_list', 1),
    'type' => MENU_LOCAL_TASK,
    'file' => 'includes/campaign_monitor_subscribers.pages.inc',
    'weight' => 2,
  );
  $items['cm-list/%cm_list/subscribers/unsubscribed'] = array(
    'title' => 'Unsubscribed',
    'page callback' => 'campaign_monitor_subscribers_list',
    'page arguments' => array(1, 3),
    'access callback' => 'entity_access',
    'access arguments' => array('update', 'cm_list', 1),
    'type' => MENU_LOCAL_TASK,
    'file' => 'includes/campaign_monitor_subscribers.pages.inc',
    'weight' => 3,
  );
  $items['cm-list/%cm_list/subscribers/bounced'] = array(
    'title' => 'Bounced',
    'page callback' => 'campaign_monitor_subscribers_list',
    'page arguments' => array(1, 3),
    'access callback' => 'entity_access',
    'access arguments' => array('update', 'cm_list', 1),
    'type' => MENU_LOCAL_TASK,
    'file' => 'includes/campaign_monitor_subscribers.pages.inc',
    'weight' => 4,
  );
  $items['cm-list/%cm_list/subscribers/deleted'] = array(
    'title' => 'Deleted',
    'page callback' => 'campaign_monitor_subscribers_list',
    'page arguments' => array(1, 3),
    'access callback' => 'entity_access',
    'access arguments' => array('update', 'cm_list', 1),
    'type' => MENU_LOCAL_TASK,
    'file' => 'includes/campaign_monitor_subscribers.pages.inc',
    'weight' => 5,
  );
  $items['cm-list/%cm_list/add-subscriber'] = array(
    'title' => 'Add Subscriber',
    'description' => 'Add subscriber to Campaign Monitor.',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('cm_subscriber_form', 1),
    'access callback' => 'entity_access',
    'access arguments' => array('update', 'cm_list', 1),
    'file' => 'includes/campaign_monitor_subscribers.admin.inc',
    'type' => MENU_CALLBACK,
  );
  $items['cm-list/%cm_list/subscribers/history'] = array(
    'title' => 'Subscriber History',
    'description' => 'Add subscriber to list.',
    'page callback' => 'campaign_monitor_subscribers_subscriber_history',
    'page arguments' => array(1),
    'access callback' => 'campaign_monitor_subscribers_update_access',
    'access arguments' => array(1),
    'file' => 'includes/campaign_monitor_subscribers.pages.inc',
    'type' => MENU_CALLBACK,
  );
  $items['cm-list/%cm_list/subscribers/delete'] = array(
    'title' => 'Delete Subscriber',
    'description' => 'Delete subscriber from list.',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('campaign_monitor_subscribers_delete_form', 1),
    'access callback' => 'campaign_monitor_subscribers_update_access',
    'access arguments' => array(1),
    'file' => 'includes/campaign_monitor_subscribers.admin.inc',
    'type' => MENU_CALLBACK,
  );
  $items['cm-list/%cm_list/subscribers/update'] = array(
    'title' => 'Update Subscriber',
    'description' => 'Update a subscriber.',
    'page callback' => 'campaign_monitor_subscribers_update_page',
    'page arguments' => array(1),
    'access callback' => 'campaign_monitor_subscribers_update_access',
    'access arguments' => array(1),
    'file' => 'includes/campaign_monitor_subscribers.admin.inc',
    'type' => MENU_CALLBACK,
  );

  return $items;
}

/**
 * Implements hook_permission().
 */
function campaign_monitor_subscribers_permission() {
  return array(
    'create subscriber' => array(
      'title' => t('Create subscriber'),
      'description' => t('Access to create Campaign Monitor subscribers'),
    ),
    'view own subscribers' => array(
      'title' => t('View own subscribers'),
      'description' => t('Access to view own Campaign Monitor subscribers'),
    ),
    'edit own subscribers' => array(
      'title' => t('Edit own subscribers'),
      'description' => t('Access to edit own Campaign Monitor subscribers'),
    ),
    'delete own subscribers' => array(
      'title' => t('Delete own subscribers'),
      'description' => t('Access to delete own Campaign Monitor subscribers'),
    ),
  );
}

/**
 * Implements hook_entity_info().
 * Inform the base system and the Field API about one or more entity types.
 */
function campaign_monitor_subscribers_entity_info() {
  $info = array();
  $info['cm_subscriber'] = array(
    'label' => t('Subscriber'),
    'plural label' => t('Subscribers'),
    'base table' => 'campaign_monitor_subscribers',
    'entity keys' => array(
      'id' => 'id',
      'label' => 'email',
    ),
    'static cache' => TRUE,
    'entity class' => 'CmSubscriberEntity',
    'controller class' => 'CmSubscriberEntityController',
    'views controller class' => 'EntityDefaultViewsController',
    'module' => 'campaign_monitor_subscribers',
    'view modes' => array(
      'full' => array(
        'label' => t('Full content'),
        'custom settings' => TRUE,
      ),
    ),
    'bundles' => array(
      'cm_subscriber' => array(
        'label' => t('Campaign Monitor Subscriber'),
        'admin' => array(
          'path' => 'admin/campaign-monitor/subscribers',
        ),
      ),
    ),
    'uri callback' => 'entity_class_uri',
  );
  return $info;
}

/**
 * Callback for returning a list of subsriber states.
 */
function campaign_monitor_subscribers_status_list($subscriber) {
  $statuses = array(
    'Active',
    'Unconfirmed',
    'Unsubscribed',
    'Bounced',
    'Deleted',
  );
  return drupal_map_assoc($statuses);
}

function campaign_monitor_subscribers_update_access($list) {
  $access = !empty($_GET['email']) && entity_access('update', 'cm_list', $list);
  return $access;
}
