<?php

/**
 * Implements hook_menu().
 */
function campaign_monitor_lists_menu() {
  $items = array();
  $items['cm-client/%cm_client/lists'] = array(
    'title' => 'Lists',
    'page callback' => 'campaign_monitor_lists_list',
    'page arguments' => array(1),
    'access callback' => 'entity_access',
    'access arguments' => array('update', 'cm_client', 1),
    'type' => MENU_LOCAL_TASK,
    'file' => 'includes/campaign_monitor_lists.pages.inc',
    'weight' => -8,
  );
  $items['cm-client/%cm_client/lists/view'] = array(
    'title' => 'View',
    'type' => MENU_DEFAULT_LOCAL_TASK,
    'weight' => -10,
  );
  $items['cm-client/%cm_client/lists/import'] = array(
    'title' => 'Import',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('campaign_monitor_lists_import_form', 1),
    'access callback' => 'entity_access',
    'access arguments' => array('update', 'cm_client', 1),
    'type' => MENU_LOCAL_TASK,
    'file' => 'includes/campaign_monitor_lists.admin.inc',
    'weight' => -8,
  );
  $items['cm-client/%cm_client/lists/add'] = array(
    'title' => 'Create list',
    'description' => 'Add list to Campaign Monitor.',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('cm_list_form', NULL, 1),
    'access arguments' => array('administer campaign monitor'),
    'file' => 'includes/campaign_monitor_lists.admin.inc',
    'type' => MENU_LOCAL_ACTION,
  );
  // Lists
  $items['cm-list/%cm_list'] = array(
    'type' => MENU_CALLBACK,
    'title' => 'List',
    'title callback' => 'entity_label',
    'title arguments' => array('cm_list', 1),
    'page callback' => 'campaign_monitor_lists_cm_list_view', // change to 'entity_ui_entity_page_view' to show default extra fields.
    'page arguments' => array(1),
    'access callback' => 'entity_access',
    'access arguments' => array('view', 'cm_list', 1),
    'file' => 'includes/campaign_monitor_lists.pages.inc',
  );
  $items['cm-list/%cm_list/view'] = array(
    'title' => 'Summary',
    'type' => MENU_DEFAULT_LOCAL_TASK,
    'weight' => -10,
  );
  $items['cm-list/%cm_list/edit'] = array(
    'title' => 'Edit',
    'page callback' => 'entity_ui_get_form',
    'page arguments' => array('cm_list', 1, 'edit'),
    'access callback' => 'entity_access',
    'access arguments' => array('update', 'cm_list', 1),
    'type' => MENU_LOCAL_TASK,
    'file' => 'includes/campaign_monitor_lists.admin.inc',
    'weight' => -9,
  );
  $items['cm-list/%cm_list/delete'] = array(
    'title' => 'Delete',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('cm_list_delete_form', 1),
    'access callback' => 'entity_access',
    'access arguments' => array('delete', 'cm_list', 1),
    'type' => MENU_LOCAL_TASK,
    'file' => 'includes/campaign_monitor_lists.admin.inc',
    'weight' => -8,
  );
  $items['cm-list/%cm_list/raw'] = array(
    'type' => MENU_LOCAL_TASK,
    'title' => 'Preview',
    'page callback' => 'campaign_monitor_lists_cm_list_view', // change to 'entity_ui_entity_page_view' to show default extra fields.
    'page arguments' => array(1, 'raw'),
    'access callback' => 'entity_access',
    'access arguments' => array('view', 'cm_list', 1),
    'file' => 'includes/campaign_monitor_lists.pages.inc',
    'weight' => -7,
    'options' => array('attributes' => array('target' => '_blank')),
  );
  $items['cm-list/%cm_list/stats'] = array(
    'type' => MENU_LOCAL_TASK,
    'title' => 'Statistics',
    'page callback' => 'campaign_monitor_lists_stats',
    'page arguments' => array(1),
    'access callback' => 'entity_access',
    'access arguments' => array('view', 'cm_list', 1),
    'file' => 'includes/campaign_monitor_lists.pages.inc',
    'weight' => -6,
  );
  $items['cm-list/webhook'] = array(
    'title' => 'BEI List webhooks endpoint',
    'type' => MENU_CALLBACK,
    'page callback' => 'campaign_monitor_lists_webhook_callback',
    'access callback' => 'campaign_monitor_webhook_access',
    'access arguments' => array(2),
    'file' => 'includes/campaign_monitor_lists.admin.inc',
  );
  $items['cm-list/%cm_list/webhooks'] = array(
    'type' => MENU_LOCAL_TASK,
    'title' => 'Webhooks',
    'page callback' => 'campaign_monitor_lists_webhooks', // change to 'entity_ui_entity_page_view' to show default extra fields.
    'page arguments' => array(1),
    'access arguments' => array('administer campaign monitor'),
    'file' => 'includes/campaign_monitor_lists.pages.inc',
    'weight' => -5
  );
  $items['cm-list/%cm_list/webhooks/add'] = array(
    'title' => 'Add Webhook',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('cm_webhook_add_form', 1),
    'access arguments' => array('administer campaign monitor'),
    'type' => MENU_LOCAL_ACTION,
    'file' => 'includes/campaign_monitor_lists.admin.inc',
  );
  $items['cm-webhook/%cm_webhook/deactivate'] = array(
    'title' => 'Deactivate webhook',
    'page callback' => 'campaign_monitor_lists_webhook_deactivate',
    'page arguments' => array(1),
    'access arguments' => array('administer campaign monitor'),
    'type' => MENU_CALLBACK,
    'file' => 'includes/campaign_monitor_lists.admin.inc',
  );
  $items['cm-webhook/%cm_webhook/activate'] = array(
    'title' => 'Active webhook',
    'page callback' => 'campaign_monitor_lists_webhook_activate',
    'page arguments' => array(1),
    'access arguments' => array('administer campaign monitor'),
    'type' => MENU_CALLBACK,
    'file' => 'includes/campaign_monitor_lists.admin.inc',
  );
  $items['cm-webhook/%cm_webhook/test'] = array(
    'title' => 'Test webhook',
    'page callback' => 'campaign_monitor_lists_webhook_test',
    'page arguments' => array(1),
    'access arguments' => array('administer campaign monitor'),
    'type' => MENU_CALLBACK,
    'file' => 'includes/campaign_monitor_lists.admin.inc',
  );
  $items['cm-webhook/%cm_webhook/delete'] = array(
    'title' => 'Delete webhook',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('cm_webhook_delete_form', 1),
    'access arguments' => array('administer campaign monitor'),
    'type' => MENU_CALLBACK,
    'file' => 'includes/campaign_monitor_lists.admin.inc',
  );
  return $items;
}

/**
 * Implements hook_permission().
 */
function campaign_monitor_lists_permission() {
  return array(
    'create list' => array(
      'title' => t('Create list'),
      'description' => t('Access to create Campaign Monitor lists'),
    ),
    'view own lists' => array(
      'title' => t('View own lists'),
      'description' => t('Access to view own Campaign Monitor lists'),
    ),
    'edit own lists' => array(
      'title' => t('Edit own lists'),
      'description' => t('Access to edit own Campaign Monitor lists'),
    ),
  );
}

/**
 * Implements hook_entity_info().
 * Inform the base system and the Field API about one or more entity types.
 */
function campaign_monitor_lists_entity_info() {
  $info = array();
  $info['cm_list'] = array(
    'label' => t('List'),
    'plural label' => t('Lists'),
    'base table' => 'campaign_monitor_lists',
    'entity keys' => array(
      'id' => 'id',
      'label' => 'title',
    ),
    'static cache' => TRUE,
    'entity class' => 'ListEntity',
    'controller class' => 'ListEntityController',
    'views controller class' => 'EntityDefaultViewsController',
    'module' => 'campaign_monitor_lists',
    'view modes' => array(
      'full' => array(
        'label' => t('Full content'),
        'custom settings' => TRUE,
      ),
      'raw' => array(
        'label' => t('Raw content'),
        'custom settings' => FALSE,
      ),
    ),
    'fieldable' => TRUE,
    'bundles' => array(
      'cm_list' => array(
        'label' => t('Campaign Monitor List'),
        'admin' => array(
          'path' => 'admin/campaign-monitor/lists',
        ),
      ),
    ),
    'access callback' => 'campaign_monitor_lists_access',
    'admin ui' => array(
      'path' => 'admin/campaign-monitor/lists',
      'controller class' => 'ListEntityUIController',
      'access arguments' => array('administer campaign monitor'),
      'file' => 'includes/campaign_monitor_lists.admin.inc',
    ),
    'uri callback' => 'entity_class_uri',
    'load hook' => 'cm_list_load',
  );
  $info['cm_webhook'] = array(
    'label' => t('Webhook'),
    'plural label' => t('Webhooks'),
    'base table' => 'campaign_monitor_list_webhooks',
    'entity keys' => array(
      'id' => 'id',
      'label' => 'webhook_id',
    ),
    'static cache' => TRUE,
    'entity class' => 'WebhookEntity',
    'controller class' => 'EntityAPIController',
    'views controller class' => 'EntityDefaultViewsController',
    'module' => 'campaign_monitor_lists',
    'bundles' => array(),
    'access callback' => 'campaign_monitor_lists_webhooks_access',
    'uri callback' => 'entity_class_uri',
    'load hook' => 'cm_webhook_load',
  );
  return $info;
}
/**
 * Implements hook_entity_property_info_alter().
 */
function campaign_monitor_lists_entity_property_info_alter(&$info) {
  $properties = &$info['cm_list']['properties'];
  $properties['uid'] = array(
    'label' => t('User'),
    'type' => 'user',
    'description' => t('The user associated with the list'),
    'setter callback' => 'entity_property_verbatim_set',
    'setter permission' => 'administer campaign monitor',
    'schema field' => 'uid',
  );
  $properties['cid'] = array(
    'label' => t('Client'),
    'type' => 'cm_client',
    'description' => t('The client entity associated with the list'),
    'setter callback' => 'entity_property_verbatim_set',
    'setter permission' => 'administer campaign monitor',
    'schema field' => 'cid',
  );
  $properties['edit_url'] = array(
    'label' => t('Edit Link'),
    'description' => t('The URL of the list\'s edit page.'),
    'getter callback' => 'campaign_monitor_lists_get_properties',
    'type' => 'uri',
    'computed' => TRUE,
    'entity views field' => TRUE,
  );
  $properties['delete_url'] = array(
    'label' => t('Delete Link'),
    'description' => t('The URL to delete a list.'),
    'getter callback' => 'campaign_monitor_lists_get_properties',
    'type' => 'uri',
    'computed' => TRUE,
    'entity views field' => TRUE,
  );
  $properties['preview_url'] = array(
    'label' => t('Preview Link'),
    'description' => t('The URL to preview a list template.'),
    'getter callback' => 'campaign_monitor_lists_get_properties',
    'type' => 'uri',
    'computed' => TRUE,
    'entity views field' => TRUE,
  );
  $properties['created'] = array(
    'label' => t('Date created'),
    'description' => t('The date the list was created.'),
    'type' => 'date',
    'schema field' => 'created',
    'setter callback' => 'entity_property_verbatim_set',
  );
  $properties['changed'] = array(
    'label' => t('Date updated'),
    'description' => t('The date the list was last updated.'),
    'type' => 'date',
    'schema field' => 'changed',
    'setter callback' => 'entity_property_verbatim_set',
  );
}
/**
 * Callback for getting subscriber properties.
 *
 */
function campaign_monitor_lists_get_properties($list, array $options, $name, $entity_type) {
  switch ($name) {
    case 'edit_url':
      $options = array('query' => drupal_get_destination());
      return url('cm-list/' . entity_id($entity_type, $list) . '/edit', $options);
      break;
    case 'delete_url':
      $options = array('query' => drupal_get_destination());
      return url('cm-list/' . entity_id($entity_type, $list) . '/delete', $options);
      break;
    case 'preview_url':
      $options = array('query' => drupal_get_destination());
      return url('cm-list/' . entity_id($entity_type, $list) . '/raw', $options);
      break;
  }
}

/*******************************************************************************
 ********************************* List API's ****************************
 ******************************************************************************/
/**
 * Access callback for List entities.
 */
function campaign_monitor_lists_access($op, $list = NULL, $account = NULL, $entity_type = NULL) {
  global $user;
  if (!isset($account)) {
    $account = $user;
  }
  switch ($op) {
    case 'create':
      return user_access('administer campaign monitor', $account) ||
      user_access('create list', $account);
    case 'view':
      return user_access('administer campaign monitor', $account) ||
      (user_access('view own lists', $account) && ($list->uid === $account->uid));
    case 'update':
      return user_access('administer campaign monitor', $account) ||
      (user_access('edit own lists', $account) && ($list->uid === $account->uid));
    case 'delete':
      return user_access('administer campaign monitor', $account);
  }
}
/**
 * Access callback for Webhook entities.
 */
function campaign_monitor_lists_webhooks_access($op, $entity = NULL, $account = NULL, $entity_type = NULL) {
  return user_access('administer campaign monitor');
}
/**
 *  Load a list.
 */
function cm_list_load($id = NULL, $reset = FALSE){
  $ids = (isset ($id) ? array($id) : array());
  $list = cm_list_load_multiple($ids, $reset);
  return $list ? reset ($list) : FALSE;
}
function cm_list_load_multiple($ids = array(), $conditions = array(), $reset = FALSE){
  return entity_load('cm_list', $ids, $conditions, $reset);
}
/**
 *  Load a webhook.
 */
function cm_webhook_load($id = NULL, $reset = FALSE){
  $ids = (isset ($id) ? array($id) : array());
  $list = cm_webhook_load_multiple($ids, $reset);
  return $list ? reset ($list) : FALSE;
}
function cm_webhook_load_multiple($ids = array(), $conditions = array(), $reset = FALSE){
  return entity_load('cm_webhook', $ids, $conditions, $reset);
}
/**
 * Delete single list.
 */
function cm_list_delete($list) {
  
  // Delete webhooks
  db_delete('campaign_monitor_list_webhooks')
  ->condition('lid', entity_id('cm_list', $list))
  ->execute();
  
  // Delete the list entity
  entity_delete('cm_list', entity_id('cm_list', $list));
}
/**
 * Delete multiple lists.
 */
function cm_list_delete_multiple($ids) {
  entity_delete_multiple('cm_list', $ids);
}

/**
 * Implements hook_views_api().
 */
function campaign_monitor_lists_views_api() {
  return array(
    'api' => 3,
    'path' => drupal_get_path('module', 'campaign_monitor_lists') . '/views',
  );
}

/**
 * Implements hook_admin_paths().
 */
function campaign_monitor_lists_admin_paths() {
  $paths = array(
    'cm-list/*/webhooks*' => TRUE,
    'cm-webhook/*/delete' => TRUE,
    'cm-webhook/*/test' => TRUE,
  );
  return $paths;
}
/**
 * Implements hook_entity_delete().
 */
function campaign_monitor_lists_entity_delete($entity, $type) {
  if ($type == 'cm_list') {
    if (module_exists('campaign_monitor_subscribers')) {
      // Delete the referenced subscribers.
      db_delete('campaign_monitor_subscribers')
      ->condition('lid', entity_id('cm_list', $entity))
      ->execute();
    }
  }
}