<?php

/**
 * @file
 * Extended field comparator usage example.
 */

/**
 * Implements hook_node_presave().
 */
function changed_fields_extended_field_comparator_node_presave($node) {
  // Create CFNodeSubject object that will check node fields by your ExtendedFieldComparator.
  // See includes/changed_fields_extended_field_comparator.field_comparator.inc file.
  $nodeSubject = new CFNodeSubject($node, new ExtendedFieldComparator());

  // Add your observer object to CFNodeSubject.
  // See includes/changed_fields_extended_field_comparator.observer.inc file.
  $nodeSubject->attach(new ExtendedFieldComparatorObserver());

  // Check if node fields have been changed.
  $nodeSubject->notify();
}
